export const config = {
  title: 'Ahmed',
  description: `I'm Ahmed, a javascript enthusiast, full-stack developer, coffee-lover, and a student.`,
  social: {
    twitter: '@ahmedriad1_',
  },
  image: 'https://ar1.dev/images/banner.jpg',
  url: 'https://ar1.dev',
  keywords: [
    'ahmed',
    'riad',
    'Ahmed Riad',
    'ahmed riad',
    'ar1',
    'javascript',
    'blog',
    'portfolio',
    'dev',
    'typescript',
    'web',
    'web dev',
    'web development',
    'backend',
    'frontend',
  ],
}
